using OptimizationExercise.PackingHeaders.Common;
using System.Runtime.InteropServices;

namespace OptimizationExercise.PackingHeaders.FieldsImpl
{
    [StructLayout(LayoutKind.Explicit, Size = Constants.HeaderNamesCount * 8)]
    internal struct FieldData
    {
        [FieldOffset(0 * 8)]
        internal string? aardvark;
        [FieldOffset(1 * 8)]
        internal string? albatross;
        [FieldOffset(2 * 8)]
        internal string? alligator;
        [FieldOffset(3 * 8)]
        internal string? anteater;
        [FieldOffset(4 * 8)]
        internal string? antelope;
        [FieldOffset(5 * 8)]
        internal string? bat;
        [FieldOffset(6 * 8)]
        internal string? beaver;
        [FieldOffset(7 * 8)]
        internal string? bee;
        [FieldOffset(8 * 8)]
        internal string? beetle;
        [FieldOffset(9 * 8)]
        internal string? binturong;
        [FieldOffset(10 * 8)]
        internal string? bird;
        [FieldOffset(11 * 8)]
        internal string? boar;
        [FieldOffset(12 * 8)]
        internal string? buffalo;
        [FieldOffset(13 * 8)]
        internal string? butterfly;
        [FieldOffset(14 * 8)]
        internal string? camel;
        [FieldOffset(15 * 8)]
        internal string? capybara;
        [FieldOffset(16 * 8)]
        internal string? caracal;
        [FieldOffset(17 * 8)]
        internal string? cat;
        [FieldOffset(18 * 8)]
        internal string? cattle;
        [FieldOffset(19 * 8)]
        internal string? chamois;
        [FieldOffset(20 * 8)]
        internal string? chicken;
        [FieldOffset(21 * 8)]
        internal string? chimpanzee;
        [FieldOffset(22 * 8)]
        internal string? chinchilla;
        [FieldOffset(23 * 8)]
        internal string? coati;
        [FieldOffset(24 * 8)]
        internal string? cockroach;
        [FieldOffset(25 * 8)]
        internal string? cormorant;
        [FieldOffset(26 * 8)]
        internal string? cow;
        [FieldOffset(27 * 8)]
        internal string? crab;
        [FieldOffset(28 * 8)]
        internal string? crocodile;
        [FieldOffset(29 * 8)]
        internal string? cuckoo;
        [FieldOffset(30 * 8)]
        internal string? curlew;
        [FieldOffset(31 * 8)]
        internal string? deer;
        [FieldOffset(32 * 8)]
        internal string? dhole;
        [FieldOffset(33 * 8)]
        internal string? dinosaur;
        [FieldOffset(34 * 8)]
        internal string? dog;
        [FieldOffset(35 * 8)]
        internal string? dogfish;
        [FieldOffset(36 * 8)]
        internal string? dolphin;
        [FieldOffset(37 * 8)]
        internal string? donkey;
        [FieldOffset(38 * 8)]
        internal string? dragonfly;
        [FieldOffset(39 * 8)]
        internal string? duck;
        [FieldOffset(40 * 8)]
        internal string? dugong;
        [FieldOffset(41 * 8)]
        internal string? eland;
        [FieldOffset(42 * 8)]
        internal string? elephant;
        [FieldOffset(43 * 8)]
        internal string? elk;
        [FieldOffset(44 * 8)]
        internal string? emu;
        [FieldOffset(45 * 8)]
        internal string? falcon;
        [FieldOffset(46 * 8)]
        internal string? ferret;
        [FieldOffset(47 * 8)]
        internal string? fish;
        [FieldOffset(48 * 8)]
        internal string? fossa;
        [FieldOffset(49 * 8)]
        internal string? fox;
        [FieldOffset(50 * 8)]
        internal string? frog;
        [FieldOffset(51 * 8)]
        internal string? gaur;
        [FieldOffset(52 * 8)]
        internal string? gazelle;
        [FieldOffset(53 * 8)]
        internal string? gecko;
        [FieldOffset(54 * 8)]
        internal string? genet;
        [FieldOffset(55 * 8)]
        internal string? gerbil;
        [FieldOffset(56 * 8)]
        internal string? gnat;
        [FieldOffset(57 * 8)]
        internal string? gnu;
        [FieldOffset(58 * 8)]
        internal string? goat;
        [FieldOffset(59 * 8)]
        internal string? goldfinch;
        [FieldOffset(60 * 8)]
        internal string? goosander;
        [FieldOffset(61 * 8)]
        internal string? gorilla;
        [FieldOffset(62 * 8)]
        internal string? goshawk;
        [FieldOffset(63 * 8)]
        internal string? grasshopper;
        [FieldOffset(64 * 8)]
        internal string? grouse;
        [FieldOffset(65 * 8)]
        internal string? guanaco;
        [FieldOffset(66 * 8)]
        internal string? gull;
        [FieldOffset(67 * 8)]
        internal string? hamster;
        [FieldOffset(68 * 8)]
        internal string? hare;
        [FieldOffset(69 * 8)]
        internal string? hawk;
        [FieldOffset(70 * 8)]
        internal string? hedgehog;
        [FieldOffset(71 * 8)]
        internal string? heron;
        [FieldOffset(72 * 8)]
        internal string? herring;
        [FieldOffset(73 * 8)]
        internal string? hoatzin;
        [FieldOffset(74 * 8)]
        internal string? hoopoe;
        [FieldOffset(75 * 8)]
        internal string? hornet;
        [FieldOffset(76 * 8)]
        internal string? horse;
        [FieldOffset(77 * 8)]
        internal string? hummingbird;
        [FieldOffset(78 * 8)]
        internal string? hyena;
        [FieldOffset(79 * 8)]
        internal string? ibis;
        [FieldOffset(80 * 8)]
        internal string? iguana;
        [FieldOffset(81 * 8)]
        internal string? jackal;
        [FieldOffset(82 * 8)]
        internal string? jaguar;
        [FieldOffset(83 * 8)]
        internal string? jay;
        [FieldOffset(84 * 8)]
        internal string? kingbird;
        [FieldOffset(85 * 8)]
        internal string? kingfisher;
        [FieldOffset(86 * 8)]
        internal string? kinkajou;
        [FieldOffset(87 * 8)]
        internal string? kodkod;
        [FieldOffset(88 * 8)]
        internal string? kookaburra;
        [FieldOffset(89 * 8)]
        internal string? kowari;
        [FieldOffset(90 * 8)]
        internal string? langur;
        [FieldOffset(91 * 8)]
        internal string? lapwing;
        [FieldOffset(92 * 8)]
        internal string? lark;
        [FieldOffset(93 * 8)]
        internal string? lechwe;
        [FieldOffset(94 * 8)]
        internal string? lemur;
        [FieldOffset(95 * 8)]
        internal string? lizard;
        [FieldOffset(96 * 8)]
        internal string? llama;
        [FieldOffset(97 * 8)]
        internal string? locust;
        [FieldOffset(98 * 8)]
        internal string? lyrebird;
        [FieldOffset(99 * 8)]
        internal string? macaque;
        [FieldOffset(100 * 8)]
        internal string? macaw;
        [FieldOffset(101 * 8)]
        internal string? mallard;
        [FieldOffset(102 * 8)]
        internal string? mammoth;
        [FieldOffset(103 * 8)]
        internal string? manatee;
        [FieldOffset(104 * 8)]
        internal string? mandrill;
        [FieldOffset(105 * 8)]
        internal string? marmoset;
        [FieldOffset(106 * 8)]
        internal string? marmot;
        [FieldOffset(107 * 8)]
        internal string? meerkat;
        [FieldOffset(108 * 8)]
        internal string? mink;
        [FieldOffset(109 * 8)]
        internal string? mongoose;
        [FieldOffset(110 * 8)]
        internal string? monkey;
        [FieldOffset(111 * 8)]
        internal string? moose;
        [FieldOffset(112 * 8)]
        internal string? mouse;
        [FieldOffset(113 * 8)]
        internal string? myna;
        [FieldOffset(114 * 8)]
        internal string? narwhal;
        [FieldOffset(115 * 8)]
        internal string? newt;
        [FieldOffset(116 * 8)]
        internal string? nightingale;
        [FieldOffset(117 * 8)]
        internal string? nilgai;
        [FieldOffset(118 * 8)]
        internal string? ocelot;
        [FieldOffset(119 * 8)]
        internal string? octopus;
        [FieldOffset(120 * 8)]
        internal string? okapi;
        [FieldOffset(121 * 8)]
        internal string? olingo;
        [FieldOffset(122 * 8)]
        internal string? opossum;
        [FieldOffset(123 * 8)]
        internal string? ostrich;
        [FieldOffset(124 * 8)]
        internal string? owl;
        [FieldOffset(125 * 8)]
        internal string? ox;
        [FieldOffset(126 * 8)]
        internal string? oyster;
        [FieldOffset(127 * 8)]
        internal string? panda;
        [FieldOffset(128 * 8)]
        internal string? panther;
        [FieldOffset(129 * 8)]
        internal string? peafowl;
        [FieldOffset(130 * 8)]
        internal string? pelican;
        [FieldOffset(131 * 8)]
        internal string? penguin;
        [FieldOffset(132 * 8)]
        internal string? pheasant;
        [FieldOffset(133 * 8)]
        internal string? pig;
        [FieldOffset(134 * 8)]
        internal string? pigeon;
        [FieldOffset(135 * 8)]
        internal string? pika;
        [FieldOffset(136 * 8)]
        internal string? pony;
        [FieldOffset(137 * 8)]
        internal string? porpoise;
        [FieldOffset(138 * 8)]
        internal string? pug;
        [FieldOffset(139 * 8)]
        internal string? quail;
        [FieldOffset(140 * 8)]
        internal string? quetzal;
        [FieldOffset(141 * 8)]
        internal string? rabbit;
        [FieldOffset(142 * 8)]
        internal string? raccoon;
        [FieldOffset(143 * 8)]
        internal string? ram;
        [FieldOffset(144 * 8)]
        internal string? rat;
        [FieldOffset(145 * 8)]
        internal string? reindeer;
        [FieldOffset(146 * 8)]
        internal string? rhea;
        [FieldOffset(147 * 8)]
        internal string? rhinoceros;
        [FieldOffset(148 * 8)]
        internal string? rook;
        [FieldOffset(149 * 8)]
        internal string? salamander;
        [FieldOffset(150 * 8)]
        internal string? sandpiper;
        [FieldOffset(151 * 8)]
        internal string? sardine;
        [FieldOffset(152 * 8)]
        internal string? sassaby;
        [FieldOffset(153 * 8)]
        internal string? seahorse;
        [FieldOffset(154 * 8)]
        internal string? seal;
        [FieldOffset(155 * 8)]
        internal string? serval;
        [FieldOffset(156 * 8)]
        internal string? sheep;
        [FieldOffset(157 * 8)]
        internal string? shrike;
        [FieldOffset(158 * 8)]
        internal string? siamang;
        [FieldOffset(159 * 8)]
        internal string? skink;
        [FieldOffset(160 * 8)]
        internal string? skipper;
        [FieldOffset(161 * 8)]
        internal string? skunk;
        [FieldOffset(162 * 8)]
        internal string? sloth;
        [FieldOffset(163 * 8)]
        internal string? snake;
        [FieldOffset(164 * 8)]
        internal string? spider;
        [FieldOffset(165 * 8)]
        internal string? spoonbill;
        [FieldOffset(166 * 8)]
        internal string? squid;
        [FieldOffset(167 * 8)]
        internal string? squirrel;
        [FieldOffset(168 * 8)]
        internal string? starfish;
        [FieldOffset(169 * 8)]
        internal string? tamarin;
        [FieldOffset(170 * 8)]
        internal string? tapir;
        [FieldOffset(171 * 8)]
        internal string? tarsier;
        [FieldOffset(172 * 8)]
        internal string? termite;
        [FieldOffset(173 * 8)]
        internal string? tiger;
        [FieldOffset(174 * 8)]
        internal string? toad;
        [FieldOffset(175 * 8)]
        internal string? toucan;
        [FieldOffset(176 * 8)]
        internal string? turaco;
        [FieldOffset(177 * 8)]
        internal string? turtle;
        [FieldOffset(178 * 8)]
        internal string? viper;
        [FieldOffset(179 * 8)]
        internal string? vulture;
        [FieldOffset(180 * 8)]
        internal string? wallaby;
        [FieldOffset(181 * 8)]
        internal string? wasp;
        [FieldOffset(182 * 8)]
        internal string? wildebeest;
        [FieldOffset(183 * 8)]
        internal string? wobbegong;
        [FieldOffset(184 * 8)]
        internal string? wolf;
        [FieldOffset(185 * 8)]
        internal string? wolverine;
        [FieldOffset(186 * 8)]
        internal string? wombat;
        [FieldOffset(187 * 8)]
        internal string? woodpecker;
        [FieldOffset(188 * 8)]
        internal string? worm;
        [FieldOffset(189 * 8)]
        internal string? wren;
        [FieldOffset(190 * 8)]
        internal string? yak;
        [FieldOffset(191 * 8)]
        internal string? zebra;
    }
}
